# Generated by Django 4.0.2 on 2022-02-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_address_addresscategory_delete_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressCategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.addresscategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresscategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
