# Generated by Django 4.0.2 on 2022-02-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_address_addresscategory_alter_addresscategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressCategory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.addresscategory'),
        ),
    ]
