# Generated by Django 4.0.2 on 2022-02-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_address_addresscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addressCategory',
        ),
        migrations.AddField(
            model_name='address',
            name='addressCategoryBilling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Billing', to='registration.addresscategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='addressCategoryDelivery',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Delivery', to='registration.addresscategory'),
            preserve_default=False,
        ),
    ]
